// Copyright (C) 2026 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "shim.h"

// The amalgamated Perfetto C SDK (generated by tools/gen_amalgamated --sdk c,
// see README). It bundles the full public API including the static-inline
// convenience helpers (PerfettoProducerInit, PerfettoTracingSessionCreate, ...).
#include "perfetto_c.h"

#include <cstdlib>
#include <cstring>

namespace {

// Owns a category descriptor plus deep copies of all the strings it points at.
// PerfettoTeCategoryImplCreate requires the descriptor and every string it
// references to stay alive until the category is destroyed, so the shim keeps
// its own copies rather than depending on Go-managed memory.
struct GoCategory {
  PerfettoTeCategoryImpl* impl = nullptr;
  PerfettoTeCategoryDescriptor desc{};
  char* name = nullptr;
  char* description = nullptr;
  char** tags = nullptr;
  size_t num_tags = 0;
};

char* DupStr(const char* s) {
  if (s == nullptr) {
    return nullptr;
  }
  size_t n = strlen(s) + 1;
  char* out = static_cast<char*>(malloc(n));
  if (out != nullptr) {
    memcpy(out, s, n);
  }
  return out;
}

// Accumulates the trace chunks delivered by ReadTraceBlocking into one buffer.
struct ReadAccumulator {
  char* buf = nullptr;
  size_t size = 0;
  size_t cap = 0;
};

void ReadCallback(PerfettoTracingSessionImpl*,
                  const void* data,
                  size_t size,
                  bool /*has_more*/,
                  void* user_arg) {
  auto* acc = static_cast<ReadAccumulator*>(user_arg);
  if (acc->size + size > acc->cap) {
    size_t new_cap = (acc->size + size) * 2;
    char* grown = static_cast<char*>(realloc(acc->buf, new_cap));
    if (grown == nullptr) {
      return;  // Drop the chunk on OOM rather than crash.
    }
    acc->buf = grown;
    acc->cap = new_cap;
  }
  memcpy(acc->buf + acc->size, data, size);
  acc->size += size;
}

}  // namespace

extern "C" {

void GoPerfettoInit(uint32_t backends) {
  PerfettoProducerInitArgs args = PERFETTO_PRODUCER_INIT_ARGS_INIT();
  args.backends = backends;
  PerfettoProducerInit(args);
  PerfettoTeInit();
}

void* GoPerfettoCategoryCreate(const char* name,
                               const char* desc,
                               const char* const* tags,
                               size_t num_tags) {
  auto* cat = new (std::nothrow) GoCategory();
  if (cat == nullptr) {
    return nullptr;
  }
  cat->name = DupStr(name);
  cat->description = DupStr(desc);
  cat->num_tags = num_tags;
  if (num_tags > 0) {
    cat->tags = static_cast<char**>(malloc(num_tags * sizeof(char*)));
    for (size_t i = 0; i < num_tags; ++i) {
      cat->tags[i] = DupStr(tags[i]);
    }
  }
  cat->desc.name = cat->name;
  cat->desc.desc = cat->description;
  cat->desc.tags = const_cast<const char**>(cat->tags);
  cat->desc.num_tags = num_tags;
  cat->impl = PerfettoTeCategoryImplCreate(&cat->desc);
  return cat;
}

void GoPerfettoPublishCategories(void) {
  PerfettoTePublishCategories();
}

void GoPerfettoCategoryDestroy(void* handle) {
  auto* cat = static_cast<GoCategory*>(handle);
  if (cat == nullptr) {
    return;
  }
  if (cat->impl != nullptr) {
    PerfettoTeCategoryImplDestroy(cat->impl);
  }
  for (size_t i = 0; i < cat->num_tags; ++i) {
    free(cat->tags[i]);
  }
  free(cat->tags);
  free(cat->name);
  free(cat->description);
  delete cat;
}

void GoPerfettoEmit(void* handle,
                    int32_t type,
                    const char* name,
                    const char* const* dbg_names,
                    const char* const* dbg_values,
                    size_t n_args) {
  auto* cat = static_cast<GoCategory*>(handle);
  if (cat == nullptr || cat->impl == nullptr) {
    return;
  }

  // Build the (null-terminated) array of extras. Each string debug annotation
  // needs its own PerfettoTeHlExtraDebugArgString whose header is referenced by
  // the extras array.
  PerfettoTeHlExtraDebugArgString* args = nullptr;
  const PerfettoTeHlExtra** extras = static_cast<const PerfettoTeHlExtra**>(
      malloc((n_args + 1) * sizeof(PerfettoTeHlExtra*)));
  if (n_args > 0) {
    args = static_cast<PerfettoTeHlExtraDebugArgString*>(
        malloc(n_args * sizeof(PerfettoTeHlExtraDebugArgString)));
    for (size_t i = 0; i < n_args; ++i) {
      args[i].header.type = PERFETTO_TE_HL_EXTRA_TYPE_DEBUG_ARG_STRING;
      args[i].name = dbg_names[i];
      args[i].value = dbg_values[i];
      extras[i] = &args[i].header;
    }
  }
  extras[n_args] = nullptr;

  PerfettoTeHlEmitImpl(cat->impl, type, name,
                       const_cast<PerfettoTeHlExtra* const*>(extras));
  free(args);
  free(extras);
}

void* GoPerfettoSessionCreateInProcess(void) {
  return PerfettoTracingSessionCreate(PERFETTO_BACKEND_IN_PROCESS);
}

void GoPerfettoSessionSetup(void* session, const void* cfg, size_t cfg_size) {
  // PerfettoTracingSessionSetup takes a non-const pointer but does not mutate
  // the config; the Go side owns the buffer.
  PerfettoTracingSessionSetup(static_cast<PerfettoTracingSessionImpl*>(session),
                              const_cast<void*>(cfg), cfg_size);
}

void GoPerfettoSessionStartBlocking(void* session) {
  PerfettoTracingSessionStartBlocking(
      static_cast<PerfettoTracingSessionImpl*>(session));
}

void GoPerfettoSessionStopBlocking(void* session) {
  PerfettoTracingSessionStopBlocking(
      static_cast<PerfettoTracingSessionImpl*>(session));
}

void GoPerfettoSessionReadTrace(void* session,
                                void** out_buf,
                                size_t* out_size) {
  ReadAccumulator acc;
  PerfettoTracingSessionReadTraceBlocking(
      static_cast<PerfettoTracingSessionImpl*>(session), ReadCallback, &acc);
  *out_buf = acc.buf;
  *out_size = acc.size;
}

void GoPerfettoSessionDestroy(void* session) {
  PerfettoTracingSessionDestroy(
      static_cast<PerfettoTracingSessionImpl*>(session));
}

void GoPerfettoFree(void* p) {
  free(p);
}

}  // extern "C"
